language: java
jdk:
  - openjdk8
# da bilda samo kad se pushne na master
branches:
  only:
    - master
      
install:
   cd ./events && mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:  
  ls -la && mvnw test -B



