language: java
jdk:
  - openjdk8
# da bilda samo kad se pushne na master
jobs:
include:
  - name: buildSping
    if: branch = master
    install: ./events/mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    script: ./events/mvnw test -B



