language: java
jdk:
  - openjdk8
# da bilda samo kad se pushne na master
branches:
  only:
    - master
install:
  - cd ./events
  - ls -la 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:  
  - mvn compile  # iskompajlira app i stavi .jar u traget folder
  # - cd target
  # - ls -la
  - java -jar target/events-0.0.1-SNAPSHOT.jar
  # - mvn test -B



