language: java
jdk:
  - openjdk8
# da bilda samo kad se pushne na master
branches:
  only:
    - master
      
install:
  - ls -la
  - cd ./events
  - ls -la 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:  
  - mvnw test -B



