export const EVENT_NOT_AVAILABLE = 'NOT_AVAILABLE';
export const EVENT_AVAILABLE = 'AVAILABLE';
export const EVENT_SOLD_OUT = 'SOLD_OUT';
export const EVENT_FINISHED = 'FINISHED';
export const EVENT_CANCELED = 'CANCELED';